// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for android - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAaMv6RgEPpryaqE0UkLHZ2OaOVyjRhsJ8',
//     appId: '1:324374998747:web:d6b9406dcf26591b55a6fe',
//     messagingSenderId: '324374998747',
//     projectId: 'snel-plus-firebase',
//     authDomain: 'snel-plus-firebase.firebaseapp.com',
//     storageBucket: 'snel-plus-firebase.appspot.com',
//     measurementId: 'G-3PRHEQLHZ4',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyASO3vE84pNOXYj-De7ypu5nv7SlREa_Ho',
//     appId: '1:324374998747:ios:755bef1c29544f5755a6fe',
//     messagingSenderId: '324374998747',
//     projectId: 'snel-plus-firebase',
//     storageBucket: 'snel-plus-firebase.appspot.com',
//     iosClientId: '324374998747-hvi8hqctp1qg69qjr4foiutj7ho38vv9.apps.googleusercontent.com',
//     iosBundleId: 'com.example.snelPlus2',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAaMv6RgEPpryaqE0UkLHZ2OaOVyjRhsJ8',
//     appId: '1:324374998747:web:e7a50980c435eca355a6fe',
//     messagingSenderId: '324374998747',
//     projectId: 'snel-plus-firebase',
//     authDomain: 'snel-plus-firebase.firebaseapp.com',
//     storageBucket: 'snel-plus-firebase.appspot.com',
//     measurementId: 'G-QLKX8XE4HL',
//   );
// }
